#!/usr/bin/env python3

from decimal import Decimal
import sys

def usage():
    print("Usage: float2bin <FLOAT> [digits]")
    exit()

def float2bin(f, digits):
    integer, f = f.split(".")
    f = float("0." + f)
    dec = Decimal(str(f))
    mantissa = ""
    nth = 0
    #rb = False
    while dec:
        if dec >= 1:
            mantissa += "1"
            dec = dec - 1
        else:
            if nth != 0:
                mantissa += "0"
        dec *= 2
        nth += 1
        if nth == digits + 1:
            #if dec != 0:
            #    rb = True
            break
    integer = bin(int(integer, 10))
    bin_str = integer + mantissa
    bin_num = int(integer + mantissa, 2)
    return bin_num

argv = sys.argv
if len(argv) < 2:
    usage()

arg1 = sys.argv[1]

if arg1 == "-h" or arg1 == "--help":
    usage()

digits = 16
if len(argv) > 2:
    digits = int(sys.argv[2], 10)

b = float2bin(arg1, digits)
print(b)
